window.BRANCHES = [
  {
    "slug": "computer-science",
    "name": "Computer Science Engineering",
    "group": "Computer & IT",
    "summary": "Study of algorithms, computing systems, and software that powers modern digital technology.",
    "coreSubjects": ["Data Structures & Algorithms", "Operating Systems", "Database Management Systems", "Computer Networks", "Theory of Computation", "Discrete Mathematics", "Compiler Design", "Software Engineering"],
    "coreSkills": ["Programming", "Problem solving", "System design", "Version control", "Debugging", "Data modeling", "Algorithmic thinking"],
    "tools": ["Git", "VS Code", "Docker", "Linux", "SQL", "Python", "Java"],
    "topDomains": ["software-development", "web-development", "ai-ml", "data-science", "cloud-devops", "cyber-security"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE CSE", "PhD"],
    "govExams": ["GATE", "ISRO", "BARC", "DRDO", "UPSC IES"]
  },
  {
    "slug": "artificial-intelligence-machine-learning",
    "name": "Artificial Intelligence & Machine Learning",
    "group": "Computer & IT",
    "summary": "Branch focused on building systems that learn from data and perform intelligent tasks.",
    "coreSubjects": ["Machine Learning", "Deep Learning", "Linear Algebra", "Probability & Statistics", "Natural Language Processing", "Computer Vision", "Data Structures", "Optimization Techniques"],
    "coreSkills": ["Model building", "Data preprocessing", "Mathematical reasoning", "Python programming", "Experiment design", "Feature engineering"],
    "tools": ["Python", "TensorFlow", "PyTorch", "scikit-learn", "Jupyter", "Pandas", "Git"],
    "topDomains": ["ai-ml", "data-science", "data-engineering", "software-development", "robotics-automation"],
    "higherStudies": ["M.Tech", "MS abroad", "GATE CSE", "PhD", "MBA"],
    "govExams": ["GATE", "ISRO", "DRDO", "BARC", "C-DAC"]
  },
  {
    "slug": "data-science",
    "name": "Data Science",
    "group": "Computer & IT",
    "summary": "Discipline that extracts insights and predictions from large volumes of structured and unstructured data.",
    "coreSubjects": ["Statistics", "Machine Learning", "Data Mining", "Database Systems", "Data Visualization", "Big Data Analytics", "Linear Algebra", "Programming for Data Science"],
    "coreSkills": ["Statistical analysis", "Data wrangling", "Visualization", "Programming", "Model evaluation", "Storytelling with data"],
    "tools": ["Python", "R", "SQL", "Pandas", "Tableau", "Power BI", "Jupyter"],
    "topDomains": ["data-science", "ai-ml", "data-engineering", "software-development", "product-management"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "PhD", "GATE Data Science"],
    "govExams": ["GATE", "ISRO", "RBI", "Census/NSSO", "DRDO"]
  },
  {
    "slug": "cyber-security",
    "name": "Cyber Security",
    "group": "Computer & IT",
    "summary": "Field dedicated to protecting systems, networks, and data from digital attacks and breaches.",
    "coreSubjects": ["Network Security", "Cryptography", "Ethical Hacking", "Operating Systems", "Computer Networks", "Digital Forensics", "Information Security", "Secure Coding"],
    "coreSkills": ["Threat analysis", "Penetration testing", "Incident response", "Network defense", "Scripting", "Risk assessment"],
    "tools": ["Wireshark", "Kali Linux", "Metasploit", "Nmap", "Burp Suite", "Splunk"],
    "topDomains": ["cyber-security", "cloud-devops", "software-development", "data-engineering"],
    "higherStudies": ["M.Tech", "MS abroad", "GATE CSE", "MBA", "PhD"],
    "govExams": ["GATE", "NIC", "CERT-In", "DRDO", "State PSC"]
  },
  {
    "slug": "information-technology",
    "name": "Information Technology",
    "group": "Computer & IT",
    "summary": "Branch dealing with the use of computers and networks to store, process, and share information.",
    "coreSubjects": ["Data Structures", "Web Technologies", "Database Management Systems", "Computer Networks", "Operating Systems", "Software Engineering", "Information Security", "Cloud Computing"],
    "coreSkills": ["Programming", "Web development", "Database management", "Networking", "System administration", "Problem solving"],
    "tools": ["Git", "VS Code", "SQL", "Docker", "Linux", "JavaScript", "AWS"],
    "topDomains": ["web-development", "software-development", "cloud-devops", "data-engineering", "cyber-security"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE IT", "PhD"],
    "govExams": ["GATE", "ISRO", "NIC", "BARC", "SSC"]
  },
  {
    "slug": "software-engineering",
    "name": "Software Engineering",
    "group": "Computer & IT",
    "summary": "Discipline applying engineering principles to the design, development, and maintenance of software systems.",
    "coreSubjects": ["Software Design", "Data Structures & Algorithms", "Software Testing", "Object Oriented Programming", "Database Management Systems", "Software Project Management", "Requirements Engineering", "Operating Systems"],
    "coreSkills": ["Programming", "System design", "Testing", "Version control", "Agile collaboration", "Code review"],
    "tools": ["Git", "Jira", "Docker", "VS Code", "Jenkins", "SQL", "Postman"],
    "topDomains": ["software-development", "web-development", "cloud-devops", "testing-qa", "product-management"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE CSE", "PhD"],
    "govExams": ["GATE", "ISRO", "BARC", "DRDO", "NIC"]
  },
  {
    "slug": "electronics-communication",
    "name": "Electronics and Communication Engineering",
    "group": "Electronics & Electrical",
    "summary": "Branch covering electronic circuits, communication systems, and signal transmission technologies.",
    "coreSubjects": ["Analog Electronics", "Digital Electronics", "Signals & Systems", "Communication Systems", "Electromagnetic Theory", "Microprocessors", "Control Systems", "VLSI Design"],
    "coreSkills": ["Circuit design", "Signal processing", "Embedded programming", "PCB design", "Problem solving", "Simulation"],
    "tools": ["MATLAB", "Cadence", "Xilinx", "Proteus", "Keil", "LTspice"],
    "topDomains": ["embedded-iot", "vlsi-semiconductor", "core-electrical", "robotics-automation", "software-development"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE ECE", "PhD"],
    "govExams": ["GATE", "ISRO", "DRDO", "BEL", "IES/ESE"]
  },
  {
    "slug": "electrical-engineering",
    "name": "Electrical Engineering",
    "group": "Electronics & Electrical",
    "summary": "Study of generation, transmission, distribution, and utilization of electrical power and systems.",
    "coreSubjects": ["Electrical Machines", "Power Systems", "Control Systems", "Power Electronics", "Circuit Theory", "Electromagnetic Fields", "Measurements & Instrumentation", "Signals & Systems"],
    "coreSkills": ["Circuit analysis", "Power system design", "Control design", "Simulation", "Problem solving", "Load calculation"],
    "tools": ["MATLAB", "AutoCAD Electrical", "PSpice", "ETAP", "Simulink", "PLC"],
    "topDomains": ["core-electrical", "electric-vehicles", "embedded-iot", "robotics-automation", "core-mechanical"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE EE", "PhD"],
    "govExams": ["GATE", "IES/ESE", "PGCIL", "NTPC", "SSC JE"]
  },
  {
    "slug": "electrical-electronics",
    "name": "Electrical and Electronics Engineering",
    "group": "Electronics & Electrical",
    "summary": "Combined branch spanning electrical power systems and electronic circuit technologies.",
    "coreSubjects": ["Electrical Machines", "Power Electronics", "Analog Electronics", "Digital Electronics", "Control Systems", "Power Systems", "Microcontrollers", "Circuit Theory"],
    "coreSkills": ["Circuit design", "Power electronics design", "Embedded programming", "Control design", "Simulation", "Troubleshooting"],
    "tools": ["MATLAB", "PSpice", "Proteus", "ETAP", "Keil", "PLC"],
    "topDomains": ["core-electrical", "electric-vehicles", "embedded-iot", "robotics-automation", "core-mechanical"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE EE", "PhD"],
    "govExams": ["GATE", "IES/ESE", "PGCIL", "NTPC", "BHEL"]
  },
  {
    "slug": "mechanical-engineering",
    "name": "Mechanical Engineering",
    "group": "Mechanical & Allied",
    "summary": "Broad branch dealing with design, manufacturing, and behaviour of mechanical systems and machines.",
    "coreSubjects": ["Thermodynamics", "Fluid Mechanics", "Strength of Materials", "Theory of Machines", "Machine Design", "Manufacturing Processes", "Heat Transfer", "Engineering Mechanics"],
    "coreSkills": ["CAD modeling", "Design analysis", "Manufacturing knowledge", "Thermal analysis", "Problem solving", "Prototyping"],
    "tools": ["AutoCAD", "SolidWorks", "ANSYS", "CATIA", "MATLAB", "Creo"],
    "topDomains": ["mechanical-design", "core-mechanical", "robotics-automation", "electric-vehicles", "product-management"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE ME", "PhD"],
    "govExams": ["GATE", "IES/ESE", "ISRO", "BHEL", "SSC JE"]
  },
  {
    "slug": "civil-engineering",
    "name": "Civil Engineering",
    "group": "Civil & Construction",
    "summary": "Branch focused on the design, construction, and maintenance of infrastructure and built environments.",
    "coreSubjects": ["Structural Analysis", "Geotechnical Engineering", "Fluid Mechanics", "Surveying", "Transportation Engineering", "Environmental Engineering", "Concrete Technology", "Construction Management"],
    "coreSkills": ["Structural design", "Surveying", "Estimation & costing", "Site management", "Analysis", "Drafting"],
    "tools": ["AutoCAD", "STAAD Pro", "Revit", "ETABS", "Primavera", "ArcGIS"],
    "topDomains": ["structural-civil", "core-civil", "product-management"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE CE", "PhD"],
    "govExams": ["GATE", "IES/ESE", "SSC JE", "State PSC", "CPWD"]
  },
  {
    "slug": "chemical-engineering",
    "name": "Chemical Engineering",
    "group": "Chemical & Bio",
    "summary": "Discipline applying chemistry and physics to design and operate industrial chemical processes.",
    "coreSubjects": ["Chemical Reaction Engineering", "Fluid Mechanics", "Thermodynamics", "Heat Transfer", "Mass Transfer", "Process Control", "Plant Design", "Transport Phenomena"],
    "coreSkills": ["Process design", "Simulation", "Safety analysis", "Problem solving", "Process optimization", "Data analysis"],
    "tools": ["Aspen Plus", "MATLAB", "ChemCAD", "AutoCAD", "HYSYS", "DWSIM"],
    "topDomains": ["chemical-process", "product-management", "data-science"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE CH", "PhD"],
    "govExams": ["GATE", "IOCL", "ONGC", "BARC", "IES/ESE"]
  },
  {
    "slug": "biotechnology",
    "name": "Biotechnology",
    "group": "Chemical & Bio",
    "summary": "Branch using biological systems and organisms to develop products and technologies for industry and health.",
    "coreSubjects": ["Molecular Biology", "Genetic Engineering", "Biochemistry", "Microbiology", "Bioprocess Engineering", "Immunology", "Cell Biology", "Bioinformatics"],
    "coreSkills": ["Lab techniques", "Bioprocess design", "Data analysis", "Research methodology", "Genetic analysis", "Documentation"],
    "tools": ["BLAST", "PyMOL", "R", "Python", "GraphPad Prism", "SnapGene"],
    "topDomains": ["biomedical-bioinformatics", "chemical-process", "data-science"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE BT", "PhD"],
    "govExams": ["GATE", "BARC", "CSIR", "ICMR", "State PSC"]
  },
  {
    "slug": "biomedical-engineering",
    "name": "Biomedical Engineering",
    "group": "Chemical & Bio",
    "summary": "Field applying engineering principles to medicine, healthcare devices, and biological systems.",
    "coreSubjects": ["Human Anatomy & Physiology", "Biomedical Instrumentation", "Medical Imaging", "Biomechanics", "Biomaterials", "Signal Processing", "Biosensors", "Bioelectronics"],
    "coreSkills": ["Instrumentation design", "Signal processing", "Device testing", "Problem solving", "Data analysis", "Prototyping"],
    "tools": ["MATLAB", "LabVIEW", "SolidWorks", "Python", "COMSOL", "Arduino"],
    "topDomains": ["biomedical-bioinformatics", "embedded-iot", "robotics-automation", "data-science"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE BM", "PhD"],
    "govExams": ["GATE", "BARC", "DRDO", "ICMR", "AIIMS"]
  },
  {
    "slug": "aeronautical-engineering",
    "name": "Aeronautical Engineering",
    "group": "Mechanical & Allied",
    "summary": "Branch focused on the design, development, and maintenance of aircraft within the atmosphere.",
    "coreSubjects": ["Aerodynamics", "Aircraft Structures", "Flight Mechanics", "Propulsion", "Fluid Mechanics", "Aircraft Design", "Thermodynamics", "Control Systems"],
    "coreSkills": ["Aerodynamic analysis", "CAD modeling", "Structural analysis", "Simulation", "Problem solving", "Testing"],
    "tools": ["ANSYS Fluent", "CATIA", "MATLAB", "SolidWorks", "XFLR5", "AutoCAD"],
    "topDomains": ["mechanical-design", "core-mechanical", "robotics-automation"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE AE", "PhD"],
    "govExams": ["GATE", "ISRO", "DRDO", "HAL", "IES/ESE"]
  },
  {
    "slug": "aerospace-engineering",
    "name": "Aerospace Engineering",
    "group": "Mechanical & Allied",
    "summary": "Discipline covering the design and development of aircraft and spacecraft for atmospheric and space flight.",
    "coreSubjects": ["Aerodynamics", "Space Dynamics", "Propulsion", "Aircraft Structures", "Flight Mechanics", "Orbital Mechanics", "Aerospace Materials", "Control Systems"],
    "coreSkills": ["Aerodynamic analysis", "Structural design", "Orbital analysis", "Simulation", "CAD modeling", "Problem solving"],
    "tools": ["ANSYS", "CATIA", "MATLAB", "STK", "SolidWorks", "Fluent"],
    "topDomains": ["mechanical-design", "core-mechanical", "robotics-automation"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE AE", "PhD"],
    "govExams": ["GATE", "ISRO", "DRDO", "HAL", "IES/ESE"]
  },
  {
    "slug": "automobile-engineering",
    "name": "Automobile Engineering",
    "group": "Mechanical & Allied",
    "summary": "Branch dealing with the design, manufacturing, and operation of automobiles and their systems.",
    "coreSubjects": ["Automotive Engines", "Vehicle Dynamics", "Automobile Chassis", "Thermodynamics", "Machine Design", "Transmission Systems", "Fluid Mechanics", "Manufacturing Processes"],
    "coreSkills": ["Vehicle design", "CAD modeling", "Engine analysis", "Diagnostics", "Simulation", "Problem solving"],
    "tools": ["AutoCAD", "CATIA", "ANSYS", "SolidWorks", "MATLAB", "GT-Power"],
    "topDomains": ["electric-vehicles", "mechanical-design", "core-mechanical", "robotics-automation"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE ME", "PhD"],
    "govExams": ["GATE", "IES/ESE", "ARAI", "BHEL", "SSC JE"]
  },
  {
    "slug": "industrial-engineering",
    "name": "Industrial Engineering",
    "group": "Mechanical & Allied",
    "summary": "Branch optimizing complex processes, systems, and organizations for efficiency and productivity.",
    "coreSubjects": ["Operations Research", "Production Planning", "Quality Control", "Supply Chain Management", "Work Study", "Ergonomics", "Manufacturing Processes", "Facility Planning"],
    "coreSkills": ["Process optimization", "Data analysis", "Quality management", "Modeling", "Problem solving", "Planning"],
    "tools": ["MATLAB", "Minitab", "Arena", "Excel", "SAP", "AutoCAD"],
    "topDomains": ["core-mechanical", "product-management", "data-science", "mechanical-design"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE ME", "PhD"],
    "govExams": ["GATE", "IES/ESE", "BHEL", "SAIL", "SSC JE"]
  },
  {
    "slug": "production-engineering",
    "name": "Production Engineering",
    "group": "Mechanical & Allied",
    "summary": "Branch combining manufacturing technology with management to produce goods efficiently and economically.",
    "coreSubjects": ["Manufacturing Processes", "Metrology", "Machine Tools", "Production Planning", "Material Science", "Machine Design", "Quality Control", "Operations Research"],
    "coreSkills": ["Manufacturing knowledge", "CAD/CAM", "Quality control", "Process planning", "Problem solving", "Measurement"],
    "tools": ["AutoCAD", "SolidWorks", "ANSYS", "Mastercam", "Minitab", "SAP"],
    "topDomains": ["core-mechanical", "mechanical-design", "product-management", "robotics-automation"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE PI", "PhD"],
    "govExams": ["GATE", "IES/ESE", "BHEL", "SAIL", "SSC JE"]
  },
  {
    "slug": "mining-engineering",
    "name": "Mining Engineering",
    "group": "Civil & Construction",
    "summary": "Discipline dealing with the extraction of minerals and resources from the earth safely and efficiently.",
    "coreSubjects": ["Mine Development", "Rock Mechanics", "Mine Surveying", "Mineral Processing", "Mine Ventilation", "Geology", "Mining Machinery", "Mine Safety"],
    "coreSkills": ["Mine planning", "Surveying", "Safety management", "Geological analysis", "Problem solving", "Estimation"],
    "tools": ["Surpac", "AutoCAD", "Datamine", "MATLAB", "ArcGIS", "MineSched"],
    "topDomains": ["core-civil", "structural-civil", "chemical-process"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE MN", "PhD"],
    "govExams": ["GATE", "Coal India", "IES/ESE", "GSI", "ONGC"]
  },
  {
    "slug": "petroleum-engineering",
    "name": "Petroleum Engineering",
    "group": "Chemical & Bio",
    "summary": "Branch focused on the exploration, extraction, and production of oil and natural gas resources.",
    "coreSubjects": ["Reservoir Engineering", "Drilling Engineering", "Petroleum Geology", "Production Engineering", "Fluid Mechanics", "Well Logging", "Thermodynamics", "Petroleum Refining"],
    "coreSkills": ["Reservoir analysis", "Drilling planning", "Simulation", "Data analysis", "Problem solving", "Well design"],
    "tools": ["Petrel", "Eclipse", "MATLAB", "PIPESIM", "AutoCAD", "CMG"],
    "topDomains": ["chemical-process", "core-mechanical", "data-science"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE PE", "PhD"],
    "govExams": ["GATE", "ONGC", "OIL", "IOCL", "GAIL"]
  },
  {
    "slug": "agricultural-engineering",
    "name": "Agricultural Engineering",
    "group": "Mechanical & Allied",
    "summary": "Branch applying engineering to agriculture, farm machinery, irrigation, and food production systems.",
    "coreSubjects": ["Farm Machinery", "Soil & Water Conservation", "Irrigation Engineering", "Post Harvest Technology", "Agricultural Process Engineering", "Surveying", "Thermodynamics", "Renewable Energy"],
    "coreSkills": ["Machinery design", "Irrigation planning", "CAD modeling", "Soil analysis", "Problem solving", "Field testing"],
    "tools": ["AutoCAD", "SolidWorks", "ArcGIS", "MATLAB", "ANSYS", "QGIS"],
    "topDomains": ["core-mechanical", "mechanical-design", "structural-civil"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE AG", "PhD"],
    "govExams": ["GATE", "ICAR", "State PSC", "FCI", "IES/ESE"]
  },
  {
    "slug": "food-technology",
    "name": "Food Technology",
    "group": "Chemical & Bio",
    "summary": "Discipline applying science and engineering to the processing, preservation, and safety of food products.",
    "coreSubjects": ["Food Chemistry", "Food Microbiology", "Food Processing", "Food Preservation", "Food Engineering", "Nutrition", "Quality Assurance", "Packaging Technology"],
    "coreSkills": ["Process design", "Quality control", "Lab analysis", "Product development", "Problem solving", "Food safety management"],
    "tools": ["MATLAB", "Minitab", "SPSS", "AutoCAD", "SAP", "Design Expert"],
    "topDomains": ["chemical-process", "product-management", "biomedical-bioinformatics"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE XL", "PhD"],
    "govExams": ["GATE", "FSSAI", "FCI", "ICAR", "State PSC"]
  },
  {
    "slug": "marine-engineering",
    "name": "Marine Engineering",
    "group": "Mechanical & Allied",
    "summary": "Branch concerned with the design, operation, and maintenance of ship machinery and marine systems.",
    "coreSubjects": ["Marine Engines", "Naval Architecture", "Thermodynamics", "Fluid Mechanics", "Marine Boilers", "Ship Construction", "Control Engineering", "Marine Electrical Systems"],
    "coreSkills": ["Machinery operation", "System maintenance", "Troubleshooting", "Safety management", "Problem solving", "Simulation"],
    "tools": ["AutoCAD", "SolidWorks", "MATLAB", "ANSYS", "MaxSurf", "Simulink"],
    "topDomains": ["core-mechanical", "mechanical-design", "core-electrical"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE ME", "PhD"],
    "govExams": ["GATE", "Indian Navy", "Shipping Corporation", "DG Shipping", "IES/ESE"]
  },
  {
    "slug": "naval-architecture",
    "name": "Naval Architecture",
    "group": "Mechanical & Allied",
    "summary": "Engineering discipline focused on the design, construction, and stability of ships and marine structures.",
    "coreSubjects": ["Ship Hydrostatics", "Ship Structures", "Ship Dynamics", "Marine Hydrodynamics", "Ship Design", "Fluid Mechanics", "Strength of Materials", "Resistance & Propulsion"],
    "coreSkills": ["Hull design", "Structural analysis", "CAD modeling", "Stability analysis", "Simulation", "Problem solving"],
    "tools": ["MaxSurf", "AutoCAD", "ANSYS Aqwa", "Rhino", "SolidWorks", "NAPA"],
    "topDomains": ["mechanical-design", "core-mechanical", "structural-civil"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE NM", "PhD"],
    "govExams": ["GATE", "Indian Navy", "Shipping Corporation", "Cochin Shipyard", "IES/ESE"]
  },
  {
    "slug": "environmental-engineering",
    "name": "Environmental Engineering",
    "group": "Civil & Construction",
    "summary": "Branch applying engineering to protect and improve air, water, and land environmental quality.",
    "coreSubjects": ["Water Treatment", "Wastewater Engineering", "Air Pollution Control", "Solid Waste Management", "Environmental Chemistry", "Hydrology", "Environmental Impact Assessment", "Fluid Mechanics"],
    "coreSkills": ["Treatment design", "Water quality analysis", "Impact assessment", "Modeling", "Problem solving", "Field sampling"],
    "tools": ["AutoCAD", "EPANET", "ArcGIS", "MATLAB", "WaterCAD", "QGIS"],
    "topDomains": ["structural-civil", "core-civil", "chemical-process"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE CE", "PhD"],
    "govExams": ["GATE", "CPCB", "State PCB", "IES/ESE", "State PSC"]
  },
  {
    "slug": "textile-engineering",
    "name": "Textile Engineering",
    "group": "Chemical & Bio",
    "summary": "Discipline dealing with the design, production, and processing of fibers, yarns, and fabrics.",
    "coreSubjects": ["Fiber Science", "Yarn Manufacturing", "Fabric Manufacturing", "Textile Chemistry", "Textile Testing", "Dyeing & Printing", "Garment Technology", "Textile Machinery"],
    "coreSkills": ["Process design", "Quality testing", "Material analysis", "Product development", "Problem solving", "Machinery operation"],
    "tools": ["AutoCAD", "TexPro", "MATLAB", "Minitab", "CAD Textile", "SAP"],
    "topDomains": ["chemical-process", "core-mechanical", "product-management"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE TF", "PhD"],
    "govExams": ["GATE", "Textile Committee", "State PSC", "NTC", "IES/ESE"]
  },
  {
    "slug": "metallurgical-engineering",
    "name": "Metallurgical Engineering",
    "group": "Mechanical & Allied",
    "summary": "Branch focused on the extraction, processing, and properties of metals and their alloys.",
    "coreSubjects": ["Physical Metallurgy", "Extractive Metallurgy", "Mechanical Metallurgy", "Thermodynamics", "Phase Transformations", "Material Characterization", "Corrosion Engineering", "Foundry Technology"],
    "coreSkills": ["Material analysis", "Process design", "Testing", "Failure analysis", "Problem solving", "Characterization"],
    "tools": ["ANSYS", "MATLAB", "Thermo-Calc", "AutoCAD", "ImageJ", "Minitab"],
    "topDomains": ["chemical-process", "core-mechanical", "mechanical-design"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE MT", "PhD"],
    "govExams": ["GATE", "SAIL", "IES/ESE", "BARC", "Coal India"]
  },
  {
    "slug": "instrumentation-engineering",
    "name": "Instrumentation Engineering",
    "group": "Electronics & Electrical",
    "summary": "Branch dealing with measurement, control, and automation of industrial processes and instruments.",
    "coreSubjects": ["Sensors & Transducers", "Process Control", "Industrial Instrumentation", "Control Systems", "Analog Electronics", "Digital Electronics", "Measurements", "PLC & SCADA"],
    "coreSkills": ["Instrumentation design", "Control tuning", "Automation", "Calibration", "Problem solving", "Simulation"],
    "tools": ["LabVIEW", "MATLAB", "PLC", "SCADA", "Proteus", "Simulink"],
    "topDomains": ["embedded-iot", "robotics-automation", "core-electrical", "core-mechanical"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE IN", "PhD"],
    "govExams": ["GATE", "IES/ESE", "BHEL", "ISRO", "NTPC"]
  },
  {
    "slug": "robotics-engineering",
    "name": "Robotics Engineering",
    "group": "Emerging",
    "summary": "Interdisciplinary branch focused on designing, building, and programming intelligent robotic systems.",
    "coreSubjects": ["Robotics Kinematics", "Control Systems", "Embedded Systems", "Machine Learning", "Sensors & Actuators", "Computer Vision", "Mechatronics", "Automation"],
    "coreSkills": ["Robot programming", "Control design", "Embedded programming", "Sensor integration", "Problem solving", "Prototyping"],
    "tools": ["ROS", "MATLAB", "Arduino", "Python", "SolidWorks", "Gazebo"],
    "topDomains": ["robotics-automation", "embedded-iot", "ai-ml", "mechanical-design", "core-electrical"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE ME", "PhD"],
    "govExams": ["GATE", "ISRO", "DRDO", "BARC", "IES/ESE"]
  },
  {
    "slug": "mechatronics-engineering",
    "name": "Mechatronics Engineering",
    "group": "Emerging",
    "summary": "Branch integrating mechanical, electronics, and computer engineering for smart automated systems.",
    "coreSubjects": ["Mechatronic Systems", "Control Systems", "Microcontrollers", "Sensors & Actuators", "Robotics", "Machine Design", "Digital Electronics", "Automation"],
    "coreSkills": ["System integration", "Embedded programming", "Control design", "CAD modeling", "Problem solving", "Prototyping"],
    "tools": ["MATLAB", "Arduino", "SolidWorks", "PLC", "LabVIEW", "ROS"],
    "topDomains": ["robotics-automation", "embedded-iot", "mechanical-design", "core-electrical", "electric-vehicles"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE ME", "PhD"],
    "govExams": ["GATE", "ISRO", "DRDO", "BHEL", "IES/ESE"]
  },
  {
    "slug": "materials-engineering",
    "name": "Materials Engineering",
    "group": "Mechanical & Allied",
    "summary": "Branch studying the structure, properties, and processing of materials for engineering applications.",
    "coreSubjects": ["Material Science", "Physical Metallurgy", "Ceramics & Polymers", "Material Characterization", "Thermodynamics", "Phase Transformations", "Composite Materials", "Nanomaterials"],
    "coreSkills": ["Material analysis", "Characterization", "Testing", "Process design", "Problem solving", "Failure analysis"],
    "tools": ["ANSYS", "MATLAB", "Thermo-Calc", "ImageJ", "AutoCAD", "Origin"],
    "topDomains": ["chemical-process", "core-mechanical", "mechanical-design"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE MT", "PhD"],
    "govExams": ["GATE", "BARC", "DRDO", "ISRO", "SAIL"]
  },
  {
    "slug": "printing-technology",
    "name": "Printing Technology",
    "group": "Mechanical & Allied",
    "summary": "Branch dealing with printing processes, packaging, and graphic reproduction technologies.",
    "coreSubjects": ["Printing Processes", "Graphic Reproduction", "Color Science", "Packaging Technology", "Print Finishing", "Printing Machinery", "Prepress Technology", "Material Science"],
    "coreSkills": ["Print production", "Color management", "Quality control", "Machinery operation", "Problem solving", "Prepress design"],
    "tools": ["Adobe InDesign", "Photoshop", "Illustrator", "CorelDRAW", "AutoCAD", "PDF Toolkit"],
    "topDomains": ["core-mechanical", "product-management", "ui-ux-design"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE ME", "PhD"],
    "govExams": ["GATE", "Govt Press", "IES/ESE", "State PSC", "SSC JE"]
  },
  {
    "slug": "ceramic-engineering",
    "name": "Ceramic Engineering",
    "group": "Chemical & Bio",
    "summary": "Branch focused on the science and technology of creating ceramic materials and products.",
    "coreSubjects": ["Ceramic Materials", "Glass Technology", "Refractory Engineering", "Material Characterization", "Thermodynamics", "Ceramic Processing", "Whiteware Technology", "Phase Equilibria"],
    "coreSkills": ["Material processing", "Characterization", "Quality control", "Testing", "Problem solving", "Kiln operation"],
    "tools": ["ANSYS", "MATLAB", "AutoCAD", "Origin", "ImageJ", "Thermo-Calc"],
    "topDomains": ["chemical-process", "core-mechanical", "mechanical-design"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE MT", "PhD"],
    "govExams": ["GATE", "BARC", "SAIL", "IES/ESE", "State PSC"]
  },
  {
    "slug": "construction-engineering",
    "name": "Construction Engineering",
    "group": "Civil & Construction",
    "summary": "Branch focused on planning, management, and execution of construction projects and infrastructure.",
    "coreSubjects": ["Construction Management", "Structural Analysis", "Concrete Technology", "Estimation & Costing", "Project Planning", "Surveying", "Building Materials", "Construction Equipment"],
    "coreSkills": ["Project management", "Estimation & costing", "Site management", "Structural design", "Scheduling", "Problem solving"],
    "tools": ["AutoCAD", "Primavera", "MS Project", "Revit", "STAAD Pro", "ETABS"],
    "topDomains": ["structural-civil", "core-civil", "product-management"],
    "higherStudies": ["M.Tech", "MS abroad", "MBA", "GATE CE", "PhD"],
    "govExams": ["GATE", "IES/ESE", "SSC JE", "CPWD", "State PSC"]
  }
];
